package com.ashley.downlightcalculator;

import android.content.Context;
import org.json.JSONArray;
import org.json.JSONObject;
import java.util.ArrayList;
import java.util.List;

public final class ProjectStore {
    private static final String PREFS="downlight_projects", KEY="projects";
    private ProjectStore() {}
    public static void save(Context c, Project p){List<Project> all=loadAll(c);for(int i=all.size()-1;i>=0;i--)if(all.get(i).name.equalsIgnoreCase(p.name))all.remove(i);all.add(0,p);write(c,all);}
    public static void delete(Context c,String name){List<Project> all=loadAll(c);all.removeIf(p->p.name.equals(name));write(c,all);}
    public static List<Project> loadAll(Context c){List<Project> out=new ArrayList<>();String raw=c.getSharedPreferences(PREFS,Context.MODE_PRIVATE).getString(KEY,"[]");try{JSONArray a=new JSONArray(raw);for(int i=0;i<a.length();i++)out.add(Project.fromJson(a.getJSONObject(i)));}catch(Exception ignored){}return out;}
    private static void write(Context c,List<Project> list){JSONArray a=new JSONArray();for(Project p:list)a.put(p.toJson());c.getSharedPreferences(PREFS,Context.MODE_PRIVATE).edit().putString(KEY,a.toString()).apply();}
    public static class Project {
        public String name="Untitled",layout="4 x 3 + Centre",roomShape="Rectangle",roomType="General";
        public double length=4800,width=3500,ceiling=2400,offset=600,shapeA=1500,shapeB=1200,cutoutDiameter=70,clearance=30,highestOutletHeight=2250;
        public int cols=4,rows=3;public boolean grid=true,measurements=true,bathroomWaterJets=false,bathroomRcd30mA=true;public String bathroomIpRating="IP65";
        public List<LayoutEngine.PointM> points=new ArrayList<>();public List<LayoutEngine.ExclusionZone> exclusions=new ArrayList<>();public List<LayoutEngine.KitchenRun> kitchenRuns=new ArrayList<>();public List<LayoutEngine.BathroomFixture> bathroomFixtures=new ArrayList<>();
        JSONObject toJson(){JSONObject o=new JSONObject();try{o.put("units","mm");o.put("name",name);o.put("layout",layout);o.put("roomShape",roomShape);o.put("roomType",roomType);o.put("length",length);o.put("width",width);o.put("ceiling",ceiling);o.put("offset",offset);o.put("shapeA",shapeA);o.put("shapeB",shapeB);o.put("cutoutDiameter",cutoutDiameter);o.put("clearance",clearance);o.put("cols",cols);o.put("rows",rows);o.put("grid",grid);o.put("measurements",measurements);o.put("highestOutletHeight",highestOutletHeight);o.put("bathroomWaterJets",bathroomWaterJets);o.put("bathroomRcd30mA",bathroomRcd30mA);o.put("bathroomIpRating",bathroomIpRating);JSONArray pts=new JSONArray();for(LayoutEngine.PointM p:points){JSONObject q=new JSONObject();q.put("x",p.x);q.put("y",p.y);pts.put(q);}o.put("points",pts);JSONArray zs=new JSONArray();for(LayoutEngine.ExclusionZone z:exclusions){JSONObject q=new JSONObject();q.put("name",z.name);q.put("x",z.x);q.put("y",z.y);q.put("w",z.width);q.put("h",z.height);zs.put(q);}o.put("zones",zs);JSONArray ks=new JSONArray();for(LayoutEngine.KitchenRun k:kitchenRuns){JSONObject q=new JSONObject();q.put("name",k.name);q.put("wall",k.wall);q.put("start",k.start);q.put("end",k.end);q.put("cupboardDepth",k.wallCupboardDepth);q.put("worktopDepth",k.worktopDepth);q.put("taskLineOffset",k.taskLineOffset);ks.put(q);}o.put("kitchenRuns",ks);JSONArray bfs=new JSONArray();for(LayoutEngine.BathroomFixture f:bathroomFixtures){JSONObject q=new JSONObject();q.put("name",f.name);q.put("type",f.type);q.put("x",f.x);q.put("y",f.y);q.put("w",f.width);q.put("h",f.height);bfs.put(q);}o.put("bathroomFixtures",bfs);}catch(Exception ignored){}return o;}
        static Project fromJson(JSONObject o){Project p=new Project();try{boolean legacy=!"mm".equals(o.optString("units",""));p.name=o.optString("name",p.name);p.layout=o.optString("layout",p.layout);p.roomShape=o.optString("roomShape",p.roomShape);p.roomType=o.optString("roomType",p.roomType);if("Bathroom".equals(p.roomType))p.roomType="Bathroom / Wetroom";p.length=o.optDouble("length",p.length);p.width=o.optDouble("width",p.width);p.ceiling=o.optDouble("ceiling",p.ceiling);p.offset=o.optDouble("offset",p.offset);p.shapeA=o.optDouble("shapeA",p.shapeA);p.shapeB=o.optDouble("shapeB",p.shapeB);p.cutoutDiameter=o.optDouble("cutoutDiameter",p.cutoutDiameter);p.clearance=o.optDouble("clearance",p.clearance);p.cols=o.optInt("cols",p.cols);p.rows=o.optInt("rows",p.rows);p.grid=o.optBoolean("grid",true);p.measurements=o.optBoolean("measurements",true);p.highestOutletHeight=o.optDouble("highestOutletHeight",2250);p.bathroomWaterJets=o.optBoolean("bathroomWaterJets",false);p.bathroomRcd30mA=o.optBoolean("bathroomRcd30mA",true);p.bathroomIpRating=o.optString("bathroomIpRating","IP65");JSONArray pts=o.optJSONArray("points");if(pts!=null)for(int i=0;i<pts.length();i++){JSONObject q=pts.getJSONObject(i);p.points.add(new LayoutEngine.PointM(q.optDouble("x"),q.optDouble("y")));}JSONArray zs=o.optJSONArray("zones");if(zs!=null)for(int i=0;i<zs.length();i++){JSONObject q=zs.getJSONObject(i);p.exclusions.add(new LayoutEngine.ExclusionZone(q.optString("name","Exclusion"),q.optDouble("x"),q.optDouble("y"),q.optDouble("w"),q.optDouble("h")));}JSONArray ks=o.optJSONArray("kitchenRuns");if(ks!=null)for(int i=0;i<ks.length();i++){JSONObject q=ks.getJSONObject(i);p.kitchenRuns.add(new LayoutEngine.KitchenRun(q.optString("name","Kitchen run"),q.optString("wall","Top"),q.optDouble("start"),q.optDouble("end"),q.optDouble("cupboardDepth",350),q.optDouble("worktopDepth",600),q.optDouble("taskLineOffset",650)));}JSONArray bfs=o.optJSONArray("bathroomFixtures");if(bfs!=null)for(int i=0;i<bfs.length();i++){JSONObject q=bfs.getJSONObject(i);p.bathroomFixtures.add(new LayoutEngine.BathroomFixture(q.optString("name","Bath/Shower"),q.optString("type","Bath"),q.optDouble("x"),q.optDouble("y"),q.optDouble("w",800),q.optDouble("h",1700)));}if(legacy){p.length*=1000;p.width*=1000;p.ceiling*=1000;p.offset*=1000;p.shapeA*=1000;p.shapeB*=1000;for(LayoutEngine.PointM q:p.points){q.x*=1000;q.y*=1000;}for(LayoutEngine.ExclusionZone z:p.exclusions){z.x*=1000;z.y*=1000;z.width*=1000;z.height*=1000;}for(LayoutEngine.KitchenRun k:p.kitchenRuns){k.start*=1000;k.end*=1000;k.wallCupboardDepth*=1000;k.worktopDepth*=1000;k.taskLineOffset*=1000;}for(LayoutEngine.BathroomFixture f:p.bathroomFixtures){f.x*=1000;f.y*=1000;f.width*=1000;f.height*=1000;}p.highestOutletHeight*=1000;}}catch(Exception ignored){}return p;}
    }
}
